---
- hosts: all
  become: yes
  tasks:
    - name: Copy files to the server
      copy:
        src: /workspace/build/
        dest: /var/www/html/
    - name: Restart the web server
      service:
        name: apache2
        state: restarted
